controller:
  hcloudToken:
    existingSecret:
      name: hcloud
      key: token
  hcloudVolumeDefaultLocation: nbg1

storageClasses:
  - name: hcloud-volumes
    defaultStorageClass: true
    reclaimPolicy: Delete
